export const ORDER_STATUS = {
  ORDERING: 'ORDERING',
  ACCEPT_PENDING: 'ACCEPT_PENDING',
  ACCEPTED: 'ACCEPTED',
  SHIPPING_PENDING: 'SHIPPING_PENDING',
  RETURN_PENDING: 'RETURN_PENDING',
  SYSTEM_CANCEL: 'SYSTEM_CANCEL',
  REFUNDED: 'REFUNDED',
  DENIED: 'DENIED',
  COMPLETED: 'COMPLETED',
};

export default ORDER_STATUS;
