export const STATUS = {
  NOT_HANDLE: 'NOT_HANDLE',
  REQUEST_PENDING: 'REQUEST_PENDING',
  REQUEST_DENIED: 'REQUEST_DENIED',
  REQUEST_RETURN: 'REQUEST_RETURN',
  REQUEST_RETURN_PENDING: 'REQUEST_RETURN_PENDING',
  RETURN_DENIED: 'RETURN_DENIED',
  RETURN_COMPLETED: 'RETURN_COMPLETED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUND_PROCESSING: 'REFUND_PROCESSING',
  REFUND_DENIED: 'REFUND_DENIED',
  REFUND_COMPLETED: 'REFUND_COMPLETED',
  COMPLETED: 'COMPLETED',
};

export const RETURN_STATUS = {
  SUCCESS: 'SUCCESS',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  NOT_HANDLE: 'NOT_HANDLE',
  EXCEPTION: 'EXCEPTION',
  FAILED: 'FAILED',
  DENIED: 'DENIED',
};

export const REFUND_STATUS = {
  SUCCESS: 'SUCCESS',
  PENDING: 'PENDING',
  NOT_HANDLE: 'NOT_HANDLE',
  FAILED: 'FAILED',
  DENIED: 'DENIED',
};

export const REFUND_REVIEW_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DENIED: 'DENIED',
};

export const RETURN_REVIEW_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  NOT_HANDLE: 'NOT_HANDLE',
  DENIED: 'DENIED',
};

export default {
  STATUS,
  RETURN_STATUS,
  REFUND_STATUS,
  REFUND_REVIEW_STATUS,
  RETURN_REVIEW_STATUS,
};
