export const SHIPPING_STATUS = {
  SORTING: 'SORTING',
  PENDING: 'PENDING',
  INITIAL: 'INITIAL',
  SHIPPING_PENDING: 'WAIT_RECEIVE',
  SHIPPING: 'SHIPPING',
  COMPLETED: 'COMPLETED',
};

export default SHIPPING_STATUS;
